import { AlertCircle, LoaderCircle, ShieldCheck, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import type { RoleFormValues, SystemRole } from '../../types/role'
import { PermissionMatrix } from './PermissionMatrix'
import { RoleFormFields } from './RoleFormFields'

interface EditRoleModalProps { role: SystemRole | null; loading: boolean; onSave: (id: string, values: RoleFormValues) => Promise<unknown>; onCancel: () => void }

export function EditRoleModal({ role, loading, onSave, onCancel }: EditRoleModalProps) {
  const [value, setValue] = useState<RoleFormValues>({ name: '', description: '', status: 'Active', permissions: [] })
  const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (role) { setValue({ name: role.name, description: role.description, status: role.status, permissions: role.permissions.map((permission) => ({ ...permission })) }); setError(null) } }, [role])
  if (!role) return null
  const submit = async () => { setError(null); try { await onSave(role.id, value) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update role. Please try again.') } }
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4 backdrop-blur-sm"><section role="dialog" aria-modal="true" aria-labelledby="edit-role-title" className="mx-auto my-4 w-full max-w-4xl rounded-2xl bg-white shadow-2xl dark:bg-slate-900 sm:my-8"><header className="flex items-start justify-between border-b border-slate-200 px-5 py-4 dark:border-slate-800 sm:px-6"><div><h2 id="edit-role-title" className="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white"><ShieldCheck size={19} className="text-violet-600" />Manage Role &amp; Permissions</h2><p className="mt-1 text-xs text-slate-400">Update role details and choose allowed actions per module.</p></div><button type="button" onClick={onCancel} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Close role dialog"><X size={19} /></button></header><div className="space-y-6 p-5 sm:p-6"><RoleFormFields value={value} systemRole={role.isSystem} onChange={setValue} /><div><div className="mb-3 flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-800 dark:text-slate-100">Module access</h3><p className="mt-0.5 text-xs text-slate-400">Select only the actions this role should be able to use.</p></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{value.permissions.length} assigned</span></div><PermissionMatrix permissions={value.permissions} onChange={(permissions) => setValue({ ...value, permissions })} /></div>{error && <p role="alert" className="flex items-center gap-2 rounded-xl bg-rose-50 px-3 py-2.5 text-xs font-semibold text-rose-700 dark:bg-rose-500/10 dark:text-rose-300"><AlertCircle size={15} />{error}</p>}<footer className="flex justify-end gap-2"><button type="button" onClick={onCancel} disabled={loading} className="rounded-xl px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 disabled:opacity-50 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</button><button type="button" onClick={submit} disabled={loading} className="inline-flex items-center gap-1.5 rounded-xl bg-blue-600 px-4 py-2.5 text-xs font-bold text-white shadow-lg shadow-blue-600/20 hover:bg-blue-700 disabled:opacity-60">{loading && <LoaderCircle size={14} className="animate-spin" />}{loading ? 'Saving…' : 'Save Permissions'}</button></footer></div></section></div>
}
