import type { RoleFormValues } from '../../types/role'

const inputClass = 'mt-1.5 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-xs text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-blue-400 focus:ring-4 focus:ring-blue-600/10 disabled:cursor-not-allowed disabled:bg-slate-100 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100 dark:disabled:bg-slate-800'

interface RoleFormFieldsProps { value: RoleFormValues; systemRole: boolean; onChange: (value: RoleFormValues) => void }

export function RoleFormFields({ value, systemRole, onChange }: RoleFormFieldsProps) {
  const update = <K extends keyof RoleFormValues>(key: K, next: RoleFormValues[K]) => onChange({ ...value, [key]: next })
  return <div className="grid gap-4 sm:grid-cols-2"><label className="text-[11px] font-bold text-slate-600 dark:text-slate-300">Role name<input value={value.name} disabled={systemRole} onChange={(event) => update('name', event.target.value)} placeholder="e.g. Registrar" className={inputClass} />{systemRole && <span className="mt-1 block text-[10px] font-medium text-slate-400">System role names are protected.</span>}</label><label className="text-[11px] font-bold text-slate-600 dark:text-slate-300">Status<select value={value.status} disabled={systemRole} onChange={(event) => update('status', event.target.value as RoleFormValues['status'])} className={inputClass}><option value="Active">Active</option><option value="Inactive">Inactive</option></select>{systemRole && <span className="mt-1 block text-[10px] font-medium text-slate-400">System roles remain active.</span>}</label><label className="text-[11px] font-bold text-slate-600 dark:text-slate-300 sm:col-span-2">Description<textarea value={value.description} onChange={(event) => update('description', event.target.value)} placeholder="Describe this role's responsibilities." className="mt-1.5 min-h-20 w-full resize-y rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs text-slate-700 outline-none transition placeholder:text-slate-400 focus:border-blue-400 focus:ring-4 focus:ring-blue-600/10 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-100" /></label></div>
}
