import { Pencil, ShieldAlert, Trash2, UserRound } from 'lucide-react'
import type { SystemRole } from '../../types/role'
import { RoleStatusBadge } from './RoleBadges'

interface RoleTableProps { roles: SystemRole[]; onEdit: (role: SystemRole) => void; onDelete: (role: SystemRole) => void }

export function RoleTable({ roles, onEdit, onDelete }: RoleTableProps) {
  return <div className="overflow-x-auto"><table className="w-full min-w-220 text-left"><thead className="bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-950/50"><tr><th className="px-5 py-3">Role name</th><th className="px-3 py-3">Description</th><th className="px-3 py-3">Permissions</th><th className="px-3 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{roles.map((role) => <tr key={role.id} className="text-xs text-slate-600 transition hover:bg-slate-50/80 dark:text-slate-300 dark:hover:bg-slate-800/40"><td className="px-5 py-3.5"><p className="font-bold text-slate-700 dark:text-slate-200">{role.name}</p>{role.isSystem && <p className="mt-0.5 inline-flex items-center gap-1 text-[10px] font-semibold text-violet-600 dark:text-violet-300"><ShieldAlert size={11} />System role</p>}</td><td className="max-w-100 px-3 py-3.5"><span className="block truncate text-slate-500 dark:text-slate-400">{role.description || 'No description provided.'}</span></td><td className="px-3 py-3.5"><span className="inline-flex rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-bold text-blue-700 dark:bg-blue-500/10 dark:text-blue-300">{role.permissions.length} assigned</span></td><td className="px-3 py-3.5"><RoleStatusBadge status={role.status} /></td><td className="px-5 py-3.5"><div className="flex justify-end gap-1"><button type="button" onClick={() => onEdit(role)} className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2.5 text-[11px] font-bold text-blue-600 hover:bg-blue-50 dark:text-blue-300 dark:hover:bg-blue-500/10"><Pencil size={13} />Manage</button><button type="button" onClick={() => onDelete(role)} className={`grid size-8 place-items-center rounded-lg transition ${role.isSystem ? 'text-slate-300 hover:bg-slate-100 dark:text-slate-600 dark:hover:bg-slate-800' : 'text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10'}`} aria-label={`Delete ${role.name}`} title={role.isSystem ? 'System roles cannot be deleted' : `Delete ${role.name}`}><Trash2 size={14} /></button></div></td></tr>)}{roles.length === 0 && <tr><td colSpan={5} className="px-6 py-14 text-center"><UserRound className="mx-auto mb-2 text-slate-300" size={28} /><p className="text-sm font-semibold text-slate-500 dark:text-slate-400">No roles found.</p><p className="mt-1 text-xs text-slate-400">Try adjusting your search or status filter.</p></td></tr>}</tbody></table></div>
}
