import { ChevronLeft, ChevronRight } from 'lucide-react'

interface PaginationProps { pageIndex: number; pageCount: number; pageSize: number; rowCount: number; onPrevious: () => void; onNext: () => void; onPageSizeChange: (value: number) => void; label?: string }

export function Pagination({ pageIndex, pageCount, pageSize, rowCount, onPrevious, onNext, onPageSizeChange, label = 'students' }: PaginationProps) {
  const start = rowCount ? pageIndex * pageSize + 1 : 0
  const end = Math.min((pageIndex + 1) * pageSize, rowCount)
  return <div className="flex flex-col gap-3 border-t border-slate-100 px-4 py-3.5 text-xs dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between sm:px-5"><p className="text-slate-400">Showing <span className="font-semibold text-slate-600 dark:text-slate-300">{start}–{end}</span> of {rowCount} {label}</p><div className="flex items-center gap-2"><select value={pageSize} onChange={(event) => onPageSizeChange(Number(event.target.value))} className="h-8 rounded-lg border border-slate-200 bg-white px-2 text-[11px] font-semibold text-slate-500 outline-none dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300" aria-label="Rows per page"><option value={10}>10 / page</option><option value={20}>20 / page</option><option value={50}>50 / page</option></select><button onClick={onPrevious} disabled={pageIndex === 0} className="grid size-8 place-items-center rounded-lg border border-slate-200 text-slate-500 disabled:opacity-35 dark:border-slate-700" aria-label="Previous page"><ChevronLeft size={16} /></button><span className="min-w-14 text-center font-semibold text-slate-600 dark:text-slate-300">{pageIndex + 1} / {Math.max(pageCount, 1)}</span><button onClick={onNext} disabled={pageIndex >= pageCount - 1} className="grid size-8 place-items-center rounded-lg border border-slate-200 text-slate-500 disabled:opacity-35 dark:border-slate-700" aria-label="Next page"><ChevronRight size={16} /></button></div></div>
}
