import { flexRender, getCoreRowModel, getPaginationRowModel, getSortedRowModel, useReactTable, type ColumnDef, type RowSelectionState, type SortingState } from '@tanstack/react-table'
import { ArrowDownUp, ChevronDown, Eye, Pencil, QrCode, Radio, RotateCcw, Trash2 } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useStudentStore } from '../../stores/studentStore'
import type { Student, StudentStatus } from '../../types/student'
import { StudentCard } from '../students/StudentCard'
import { StatusBadge } from '../students/StatusBadge'
import { Pagination } from './Pagination'

interface StudentTableProps { students: Student[]; onView: (student: Student) => void; onEdit: (student: Student) => void; onStatusChange: (student: Student, status: StudentStatus) => void }

function initials(student: Student) { return `${student.firstName[0]}${student.lastName[0]}` }
function fullName(student: Student) { return `${student.firstName} ${student.middleName ? `${student.middleName[0]}. ` : ''}${student.lastName}` }

export function StudentTable({ students, onView, onEdit, onStatusChange }: StudentTableProps) {
  const { selectedIds, setSelectedIds } = useStudentStore()
  const [sorting, setSorting] = useState<SortingState>([])
  const rowSelection = useMemo<RowSelectionState>(() => Object.fromEntries(selectedIds.map((id) => [id, true])), [selectedIds])
  const columns = useMemo<ColumnDef<Student>[]>(() => [
    { id: 'select', header: ({ table }) => <input type="checkbox" checked={table.getIsAllPageRowsSelected()} ref={(input) => { if (input) input.indeterminate = table.getIsSomePageRowsSelected() }} onChange={table.getToggleAllPageRowsSelectedHandler()} className="size-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500" aria-label="Select all visible students" />, cell: ({ row }) => <input type="checkbox" checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} className="size-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500" aria-label={`Select ${fullName(row.original)}`} />, enableSorting: false },
    { id: 'photo', header: 'Photo', enableSorting: false, cell: ({ row }) => <button onClick={() => onView(row.original)} className={`grid size-9 place-items-center overflow-hidden rounded-xl text-[10px] font-bold ${row.original.avatarColor}`} aria-label={`View ${fullName(row.original)}`}>{row.original.photo ? <img src={row.original.photo} alt="" className="size-full object-cover" /> : initials(row.original)}</button> },
    { accessorKey: 'studentId', header: 'Student ID', cell: ({ row }) => <span className="font-mono text-[10px] text-slate-500">{row.original.studentId}</span> },
    { id: 'fullName', accessorFn: fullName, header: 'Full name', cell: ({ row }) => <button onClick={() => onView(row.original)} className="block max-w-40 truncate text-left text-xs font-bold text-slate-700 hover:text-blue-600 dark:text-slate-200">{fullName(row.original)}</button> },
    { accessorKey: 'qrCode', header: 'QR code', cell: ({ row }) => <span title={row.original.qrCode} className="inline-flex items-center gap-1.5 font-mono text-[10px] font-medium text-slate-500"><QrCode size={15} className="text-blue-500" />{row.original.qrCode}</span> },
    { accessorKey: 'rfidNumber', header: 'RFID number', cell: ({ row }) => <span className="inline-flex items-center gap-1.5 font-mono text-[10px] text-slate-500"><Radio size={14} className="text-violet-500" />{row.original.rfidNumber}</span> },
    { accessorKey: 'courseCode', header: 'Course', cell: ({ row }) => <div><p className="text-xs font-semibold text-slate-600 dark:text-slate-300">{row.original.courseCode}</p><p className="mt-0.5 max-w-32 truncate text-[10px] text-slate-400">{row.original.course.replace('BS ', '')}</p></div> },
    { accessorKey: 'yearLevel', header: 'Year / section', cell: ({ row }) => <div className="text-[11px]"><p className="font-medium text-slate-600 dark:text-slate-300">{row.original.yearLevel}</p><p className="mt-0.5 text-slate-400">{row.original.section}</p></div> },
    { accessorKey: 'status', header: 'Status', cell: ({ row }) => <StatusBadge status={row.original.status} /> },
    { accessorKey: 'registeredAt', header: 'Registered', cell: ({ row }) => <time className="whitespace-nowrap text-[11px] text-slate-500">{new Date(`${row.original.registeredAt}T12:00:00`).toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' })}</time> },
    { id: 'actions', header: 'Actions', enableSorting: false, cell: ({ row }) => <div className="flex items-center justify-end gap-0.5"><button onClick={() => onView(row.original)} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-blue-50 hover:text-blue-600 dark:hover:bg-blue-500/10" aria-label={`View ${fullName(row.original)}`}><Eye size={15} /></button><button onClick={() => onEdit(row.original)} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800" aria-label={`Edit ${fullName(row.original)}`}><Pencil size={14} /></button>{row.original.status === 'Archived' ? <button onClick={() => onStatusChange(row.original, 'Active')} className="grid size-8 place-items-center rounded-lg text-emerald-600 hover:bg-emerald-50 dark:hover:bg-emerald-500/10" aria-label={`Restore ${fullName(row.original)}`}><RotateCcw size={14} /></button> : <button onClick={() => onStatusChange(row.original, 'Archived')} className="grid size-8 place-items-center rounded-lg text-rose-500 hover:bg-rose-50 dark:hover:bg-rose-500/10" aria-label={`Archive ${fullName(row.original)}`}><Trash2 size={14} /></button>}</div> },
  ], [onEdit, onStatusChange, onView])
  const table = useReactTable({ data: students, columns, state: { sorting, rowSelection }, enableRowSelection: true, onSortingChange: setSorting, onRowSelectionChange: (updater) => { const next = typeof updater === 'function' ? updater(rowSelection) : updater; setSelectedIds(Object.keys(next).filter((id) => next[id])) }, getRowId: (student) => student.id, getCoreRowModel: getCoreRowModel(), getSortedRowModel: getSortedRowModel(), getPaginationRowModel: getPaginationRowModel(), initialState: { pagination: { pageSize: 10 } } })
  return <section className="overflow-hidden rounded-2xl border border-slate-200/80 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="hidden overflow-x-auto lg:block"><table className="w-full min-w-[1250px] text-left"><thead className="sticky top-0 z-[1] bg-slate-50/95 text-[10px] font-bold uppercase tracking-wider text-slate-400 backdrop-blur dark:bg-slate-950/95"><tr>{table.getHeaderGroups().map((headerGroup) => headerGroup.headers.map((header) => <th key={header.id} className="whitespace-nowrap px-3 py-3 first:px-5 last:px-5"><button onClick={header.column.getToggleSortingHandler()} disabled={!header.column.getCanSort()} className="inline-flex items-center gap-1 disabled:cursor-default">{header.isPlaceholder ? null : flexRender(header.column.columnDef.header, header.getContext())}{header.column.getCanSort() && <ArrowDownUp size={11} className={header.column.getIsSorted() ? 'text-blue-600' : ''} />}</button></th>))}</tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{table.getRowModel().rows.map((row) => <tr key={row.id} className={`transition hover:bg-slate-50/80 dark:hover:bg-slate-800/50 ${row.getIsSelected() ? 'bg-blue-50/60 dark:bg-blue-500/5' : ''}`}>{row.getVisibleCells().map((cell) => <td key={cell.id} className="px-3 py-3 first:px-5 last:px-5">{flexRender(cell.column.columnDef.cell, cell.getContext())}</td>)}</tr>)}</tbody></table></div><div className="space-y-3 p-3 lg:hidden">{table.getRowModel().rows.map((row) => <StudentCard key={row.id} student={row.original} selected={row.getIsSelected()} onToggle={() => row.toggleSelected()} onView={() => onView(row.original)} onEdit={() => onEdit(row.original)} />)}</div>{table.getRowModel().rows.length === 0 && <div className="grid min-h-56 place-items-center px-5 text-center"><div><p className="text-sm font-bold text-slate-600 dark:text-slate-300">No students found</p><p className="mt-1 text-xs text-slate-400">Adjust your search or filters to see matching student records.</p></div></div>}<Pagination pageIndex={table.getState().pagination.pageIndex} pageCount={table.getPageCount()} pageSize={table.getState().pagination.pageSize} rowCount={table.getFilteredRowModel().rows.length} onPrevious={() => table.previousPage()} onNext={() => table.nextPage()} onPageSizeChange={(value) => table.setPageSize(value)} /></section>
}
