import { ArrowUpRight, UsersRound } from 'lucide-react'
import { formatNumber } from '../../utils/format'

export function StudentOverviewCard({ total, active, inactive }: { total: number; active: number; inactive: number }) {
  const percentage = Math.round((active / total) * 100)
  const circumference = 2 * Math.PI * 38
  return (
    <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900">
      <div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-800 dark:text-slate-100">Student overview</p><p className="mt-0.5 text-xs text-slate-400">Enrollment status this semester</p></div><span className="grid size-9 place-items-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-500/10 dark:text-indigo-300"><UsersRound size={19} /></span></div>
      <div className="mt-5 flex items-center gap-5"><div className="relative grid size-28 shrink-0 place-items-center"><svg className="size-28 -rotate-90" viewBox="0 0 96 96" aria-label={`${percentage}% active students`} role="img"><circle cx="48" cy="48" r="38" fill="none" stroke="currentColor" strokeWidth="8" className="text-slate-100 dark:text-slate-800" /><circle cx="48" cy="48" r="38" fill="none" stroke="currentColor" strokeWidth="8" strokeLinecap="round" strokeDasharray={circumference} strokeDashoffset={circumference * (1 - percentage / 100)} className="text-blue-600" /></svg><span className="absolute text-center text-lg font-bold text-slate-900 dark:text-white">{percentage}%<small className="block text-[9px] font-semibold uppercase tracking-wide text-slate-400">active</small></span></div><dl className="min-w-0 flex-1 space-y-3"><div className="flex justify-between text-xs"><dt className="text-slate-400">Registered</dt><dd className="font-bold text-slate-700 dark:text-slate-200">{formatNumber(total)}</dd></div><div className="flex justify-between text-xs"><dt className="inline-flex items-center gap-1.5 text-slate-500"><i className="size-2 rounded-full bg-emerald-500" />Active</dt><dd className="font-bold text-slate-700 dark:text-slate-200">{formatNumber(active)}</dd></div><div className="flex justify-between text-xs"><dt className="inline-flex items-center gap-1.5 text-slate-500"><i className="size-2 rounded-full bg-slate-300" />Inactive</dt><dd className="font-bold text-slate-700 dark:text-slate-200">{formatNumber(inactive)}</dd></div></dl></div>
      <button className="mt-5 flex w-full items-center justify-center gap-1.5 rounded-xl border border-slate-200 py-2.5 text-xs font-bold text-slate-600 transition hover:border-blue-200 hover:bg-blue-50 hover:text-blue-700 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800"><span>View student details</span><ArrowUpRight size={15} /></button>
    </section>
  )
}
