import { Eye, UserRound } from 'lucide-react'
import { formatAuditDateTime } from '../../services/auditLogService'
import type { AuditLog } from '../../types/auditLog'
import { AuditActionBadge, AuditStatusBadge } from './AuditLogBadges'

interface AuditLogsTableProps { logs: AuditLog[]; onViewDetails: (log: AuditLog) => void }

export function AuditLogsTable({ logs, onViewDetails }: AuditLogsTableProps) {
  return <div className="overflow-x-auto"><table className="w-full min-w-300 text-left"><thead className="bg-slate-50/70 text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:bg-slate-950/50"><tr><th className="px-5 py-3">Date &amp; time</th><th className="px-3 py-3">User</th><th className="px-3 py-3">User role</th><th className="px-3 py-3">Module</th><th className="px-3 py-3">Action</th><th className="px-3 py-3">Description</th><th className="px-3 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{logs.map((log) => <tr key={log.id} className="text-xs text-slate-600 transition hover:bg-slate-50/80 dark:text-slate-300 dark:hover:bg-slate-800/40"><td className="whitespace-nowrap px-5 py-3.5 text-[11px] text-slate-400">{formatAuditDateTime(log.timestamp)}</td><td className="px-3 py-3.5"><p className="font-semibold text-slate-700 dark:text-slate-200">{log.userName}</p><p className="mt-0.5 font-mono text-[10px] text-slate-400">{log.userId}</p></td><td className="px-3 py-3.5"><span className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{log.userRole}</span></td><td className="px-3 py-3.5 font-semibold text-slate-600 dark:text-slate-300">{log.module}</td><td className="px-3 py-3.5"><AuditActionBadge action={log.action} /></td><td className="max-w-72 px-3 py-3.5"><span className="block truncate text-slate-500 dark:text-slate-400">{log.description}</span></td><td className="px-3 py-3.5"><AuditStatusBadge status={log.status} /></td><td className="px-5 py-3.5 text-right"><button type="button" onClick={() => onViewDetails(log)} className="inline-flex h-8 items-center gap-1.5 rounded-lg px-2.5 text-[11px] font-bold text-blue-600 transition hover:bg-blue-50 dark:text-blue-300 dark:hover:bg-blue-500/10"><Eye size={14} />View Details</button></td></tr>)}{logs.length === 0 && <tr><td colSpan={8} className="px-6 py-14 text-center"><UserRound className="mx-auto mb-2 text-slate-300" size={28} /><p className="text-sm font-semibold text-slate-500 dark:text-slate-400">No audit logs found.</p><p className="mt-1 text-xs text-slate-400">Try adjusting the search or filters to see recorded activities.</p></td></tr>}</tbody></table></div>
}
