import { CheckCircle2, CircleAlert, LoaderCircle, Radio, ScanLine, TriangleAlert } from 'lucide-react'
import type { NotificationItem } from '../../types/dashboard'
import { useSystemSettings } from '../../hooks/useSystemSettings'
import { useNotificationStore } from '../../stores/notificationStore'

const notificationConfig = { late: { icon: CircleAlert, color: 'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-300' }, failed: { icon: ScanLine, color: 'bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-300' }, connected: { icon: Radio, color: 'bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300' }, recorded: { icon: CheckCircle2, color: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300' } }

export function NotificationPanel({ notifications, onMarkAllRead, isMarkingAllRead }: { notifications: NotificationItem[]; onMarkAllRead?: () => void; isMarkingAllRead?: boolean }) {
  const notificationsEnabled = useSystemSettings((settings) => settings.notifications.notificationsEnabled)
  const overrides = useNotificationStore((state) => state.overrides)
  const hasUnread = notifications.some((n) => {
    const override = overrides[n.id]
    return override === undefined ? n.unread : override === 'unread'
  })
  return <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between"><div><h2 className="text-base font-bold text-slate-800 dark:text-slate-100">Notifications</h2><p className="mt-1 text-xs text-slate-400">Latest system updates</p></div><button onClick={onMarkAllRead} disabled={isMarkingAllRead || !hasUnread} className="flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-700 disabled:pointer-events-none disabled:opacity-40 dark:text-blue-400">{isMarkingAllRead && <LoaderCircle size={12} className="animate-spin" />}Mark all read</button></div>{!notificationsEnabled && <div className="mt-3 flex items-start gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2.5 text-[11px] leading-4 text-amber-800 dark:border-amber-500/25 dark:bg-amber-500/10 dark:text-amber-200"><TriangleAlert size={14} className="mt-0.5 shrink-0" /><span>Notifications are currently disabled in System Settings. New alerts will not be generated until re-enabled.</span></div>}<div className="mt-3 divide-y divide-slate-100 dark:divide-slate-800">{notifications.map((notification) => { const config = notificationConfig[notification.type]; const Icon = config.icon; return <article key={notification.id} className="flex gap-3 py-3 first:pt-2"><span className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg ${config.color}`}><Icon size={15} /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="text-xs font-bold text-slate-700 dark:text-slate-200">{notification.title}</h3><div className="flex items-center gap-1 whitespace-nowrap text-[10px] text-slate-400">{(overrides[notification.id] === undefined ? notification.unread : overrides[notification.id] === 'unread') && <i className="size-1.5 rounded-full bg-blue-600" />}{notification.time}</div></div><p className="mt-1 text-[11px] leading-4 text-slate-400">{notification.description}</p></div></article>})}</div></section>
}
