import { CheckCircle2, CircleAlert, LoaderCircle, Radio, ScanLine } from 'lucide-react'
import type { NotificationItem } from '../../types/dashboard'
import { useNotificationStore } from '../../stores/notificationStore'

const notificationConfig = { late: { icon: CircleAlert, color: 'bg-amber-50 text-amber-600 dark:bg-amber-500/10 dark:text-amber-300' }, failed: { icon: ScanLine, color: 'bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-300' }, connected: { icon: Radio, color: 'bg-violet-50 text-violet-600 dark:bg-violet-500/10 dark:text-violet-300' }, recorded: { icon: CheckCircle2, color: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-500/10 dark:text-emerald-300' } }

export function NotificationPanel({ notifications, onMarkAllRead, isMarkingAllRead }: { notifications: NotificationItem[]; onMarkAllRead?: () => void; isMarkingAllRead?: boolean }) {
  const overrides = useNotificationStore((state) => state.overrides)
  const isUnread = (id: string, original: boolean) => { const o = overrides[id]; return o === undefined ? original : o === 'unread' }
  const hasUnread = notifications.some((n) => isUnread(n.id, n.unread))
  return <section className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex justify-between"><div><h2 className="text-base font-bold text-slate-800 dark:text-slate-100">Notifications</h2><p className="mt-1 text-xs text-slate-400">Latest system updates</p></div><button onClick={onMarkAllRead} disabled={!hasUnread || isMarkingAllRead} className="flex items-center gap-1.5 text-xs font-bold text-blue-600 hover:text-blue-700 disabled:cursor-not-allowed disabled:opacity-40 dark:text-blue-400">{isMarkingAllRead && <LoaderCircle size={12} className="animate-spin" />}Mark all read</button></div><div className="mt-3 divide-y divide-slate-100 dark:divide-slate-800">{notifications.map((notification) => { const config = notificationConfig[notification.type]; const Icon = config.icon; const unread = isUnread(notification.id, notification.unread); return <article key={notification.id} className="flex gap-3 py-3 first:pt-2"><span className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-lg ${config.color}`}><Icon size={15} /></span><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="text-xs font-bold text-slate-700 dark:text-slate-200">{notification.title}</h3><div className="flex items-center gap-1 whitespace-nowrap text-[10px] text-slate-400">{unread && <i className="size-1.5 rounded-full bg-blue-600" />}{notification.time}</div></div><p className="mt-1 text-[11px] leading-4 text-slate-400">{notification.description}</p></div></article>})}</div></section>
}
