import { Eye, MoreHorizontal, QrCode, Radio } from 'lucide-react'
import type { Student } from '../../types/student'
import { StatusBadge } from './StatusBadge'

interface StudentCardProps { student: Student; selected: boolean; onToggle: () => void; onView: () => void; onEdit: () => void }

export function StudentCard({ student, selected, onToggle, onView, onEdit }: StudentCardProps) {
  return <article className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex gap-3"><input type="checkbox" checked={selected} onChange={onToggle} aria-label={`Select ${student.firstName} ${student.lastName}`} className="mt-1 size-4 rounded border-slate-300 text-blue-600 focus:ring-blue-500" /><button onClick={onView} className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-xl bg-slate-100 text-xs font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{student.photo ? <img src={student.photo} alt="" className="size-full object-cover" /> : `${student.firstName[0]}${student.lastName[0]}`}</button><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><button onClick={onView} className="truncate text-left text-sm font-bold text-slate-800 hover:text-blue-600 dark:text-slate-100">{student.firstName} {student.middleName ? `${student.middleName[0]}. ` : ''}{student.lastName}</button><p className="mt-0.5 font-mono text-[10px] text-slate-400">{student.studentId}</p></div><StatusBadge status={student.status} /></div><p className="mt-3 text-xs font-medium text-slate-600 dark:text-slate-300">{student.courseCode} · {student.yearLevel}</p><p className="mt-1 text-[11px] text-slate-400">{student.section} · Registered {new Date(`${student.registeredAt}T12:00:00`).toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' })}</p></div></div><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3 dark:border-slate-800"><span className="flex items-center gap-3 text-[11px] text-slate-400"><span className="inline-flex items-center gap-1"><QrCode size={13} className="text-blue-500" />{student.qrCode}</span><span className="inline-flex items-center gap-1"><Radio size={13} className="text-violet-500" />RFID</span></span><div className="flex gap-1"><button onClick={onView} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-blue-50 hover:text-blue-600 dark:hover:bg-blue-500/10" aria-label={`View ${student.firstName}`}><Eye size={16} /></button><button onClick={onEdit} className="grid size-8 place-items-center rounded-lg text-slate-400 hover:bg-slate-100 hover:text-slate-700 dark:hover:bg-slate-800" aria-label={`Edit ${student.firstName}`}><MoreHorizontal size={17} /></button></div></div></article>
}
