import { AlertTriangle, X } from 'lucide-react'
import type { ReactNode } from 'react'

interface ConfirmationModalProps { open: boolean; title: string; description: ReactNode; confirmLabel: string; tone?: 'danger' | 'primary'; onConfirm: () => void; onCancel: () => void; loading?: boolean }

export function ConfirmationModal({ open, title, description, confirmLabel, tone = 'primary', onConfirm, onCancel, loading }: ConfirmationModalProps) {
  if (!open) return null
  return <div className="fixed inset-0 z-70 grid place-items-center bg-slate-950/45 p-4 backdrop-blur-sm" role="presentation"><section role="dialog" aria-modal="true" aria-labelledby="confirmation-title" className="w-full max-w-md rounded-2xl border border-white/40 bg-white p-5 shadow-2xl dark:border-slate-700 dark:bg-slate-900"><div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl ${tone === 'danger' ? 'bg-rose-50 text-rose-600 dark:bg-rose-500/10 dark:text-rose-300' : 'bg-blue-50 text-blue-600 dark:bg-blue-500/10 dark:text-blue-300'}`}><AlertTriangle size={20} /></span><button onClick={onCancel} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800" aria-label="Close confirmation"><X size={18} /></button></div><h2 id="confirmation-title" className="mt-4 text-lg font-bold text-slate-900 dark:text-white">{title}</h2><div className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{description}</div><div className="mt-6 flex justify-end gap-2"><button onClick={onCancel} disabled={loading} className="rounded-xl px-4 py-2.5 text-xs font-bold text-slate-600 hover:bg-slate-100 disabled:opacity-50 dark:text-slate-300 dark:hover:bg-slate-800">Cancel</button><button onClick={onConfirm} disabled={loading} className={`rounded-xl px-4 py-2.5 text-xs font-bold text-white shadow-lg disabled:opacity-60 ${tone === 'danger' ? 'bg-rose-600 shadow-rose-600/20 hover:bg-rose-700' : 'bg-blue-600 shadow-blue-600/20 hover:bg-blue-700'}`}>{loading ? 'Saving…' : confirmLabel}</button></div></section></div>
}
